name: final_project
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - anyio=3.2.1
  - appnope=0.1.2
  - argon2-cffi=20.1.0
  - attrs=20.2.0
  - backcall=0.2.0
  - bleach=3.2.1
  - brotlipy=0.7.0
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=3.0.4
  - colorama=0.4.4
  - cryptography=3.4.7
  - cycler=0.10.0
  - dbus=1.13.18
  - debugpy=1.3.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.10
  - freetype=2.10.4
  - gettext=0.19.8.1
  - gitdb=4.0.5
  - gitpython=3.1.9
  - glib=2.66.1
  - icu=68.1
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - invoke=1.6.0
  - ipykernel=6.0.1
  - ipython=7.25.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=2.11.2
  - joblib=1.0.1
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter-server-mathjax=0.2.3
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.7.1
  - jupyter_server=1.9.0
  - jupyterlab=2.2.6
  - jupyterlab_server=1.2.0
  - kiwisolver=1.3.1
  - krb5=1.19.1
  - lcms2=2.12
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcxx=12.0.1
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libopenblas=0.3.15
  - libpng=1.6.37
  - libpq=13.3
  - libsodium=1.0.18
  - libtiff=4.3.0
  - libwebp-base=1.1.0
  - llvm-openmp=11.1.0
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - natsort=7.1.1
  - nbconvert=5.5.0
  - nbdime=3.1.0
  - nbformat=5.0.8
  - ncurses=6.2
  - notebook=6.4.0
  - nspr=4.30
  - nss=3.67
  - numpy=1.21.0
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - packaging=20.4
  - pandas=1.3.0
  - pandas-flavor=0.2.0
  - pandoc=2.11
  - pandocfilters=1.4.2
  - parso=0.8.0
  - pathlib=1.0.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.1.3
  - plotly=4.11.0
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.7.1
  - pyjanitor=0.20.14
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyprojroot=0.2.0
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.9.6
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytz=2020.1
  - pyzmq=22.1.0
  - qt=5.12.9
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - readline=8.1
  - requests=2.24.0
  - requests-unixsocket=0.2.0
  - retrying=1.3.3
  - scikit-learn=0.24.2
  - scipy=1.7.0
  - seaborn=0.11.0
  - send2trash=1.7.1
  - setuptools=49.6.0
  - six=1.15.0
  - smmap=3.0.4
  - sniffio=1.2.0
  - sqlite=3.36.0
  - terminado=0.10.1
  - testpath=0.4.4
  - threadpoolctl=2.2.0
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - tzdata=2020b
  - urllib3=1.25.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - xarray=0.18.2
  - xlrd=2.0.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.3.1
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - multipledispatch==0.6.0

